DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS attendance;

ALTER TABLE IF EXISTS departments DROP CONSTRAINT IF EXISTS fk_dept_manager;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS roles;
